In [138]:
import numpy as np
import tensorflow as tf

from utils import compute_cost

RANDOM_STATE = 36   

In [139]:
#? Movie Rating
Y = np.array([
#   Toy  Matrix  Titanic  Avengers  Shrek LaLaLand
    [5, 1, 1, 5, 4, 5], # Alice
    [1, 5, 2, 5, 1, 5], # Bob
    [5, 1, 5, 3, 5, 5], # Charlie
    [2, 5, 1, 4, 1, 5], # David
    [5, 3, 4, 1, 5, 5], # Kiamehr
], dtype=np.float64)

#? Was Rated?
R = np.array([
    [1, 1, 0, 1, 1, 1],
    [1, 1, 1, 1, 0, 1],
    [1, 1, 1, 0, 1, 0],
    [1, 1, 0, 1, 1, 1],
    [1, 1, 1, 0, 1, 1],
], dtype=np.float64)

print(Y.shape)

(5, 6)


# Initialization of X, W, b Values

In [140]:
np.random.seed(RANDOM_STATE)

X = np.random.randn(6, 2,) #? Movies / Features
W = np.random.randn(5, 2,) #? Users / Features
b = np.zeros(5) #? Users 

X, W, b

(array([[ 0.67641327,  1.52109919],
        [-0.51187625,  1.15019464],
        [-0.59071681, -0.76876525],
        [-0.33500917,  0.09299944],
        [-1.37755311,  0.22791697],
        [-0.59016463, -1.29693989]]),
 array([[-1.59805879, -0.29740901],
        [-1.45155795, -0.19986179],
        [-0.55274563,  1.95845977],
        [-1.70483391,  0.91342904],
        [-0.69192222, -0.67155148]]),
 array([0., 0., 0., 0., 0.]))

# Pedicting Move Ratings 
## With Linear Regression

In [141]:
predictions = W @ X.T + b[:, None]

print("X shape:", X.shape)
print("W shape:", W.shape)
print("b shape:", b.shape)
print("\nPredictions shape:", predictions.shape)

print(predictions)


X shape: (6, 2)
W shape: (5, 2)
b shape: (5,)

Predictions shape: (5, 6)
[[-1.53333677  0.47593008  1.1726379   0.50770547  2.1336263   1.32883939]
 [-1.28586266  0.51313807  1.01110648  0.46769818  1.95404628  1.11586689]
 [ 2.60512709  2.53554728 -1.17907968  0.36731052  1.20780267 -2.21379368]
 [ 0.23624389  1.92328516  0.30486154  0.65608338  2.55668523 -0.17852988]
 [-1.48952178 -0.41823636  0.92499553  0.16934637  0.80010163  1.27930993]]


# Compute Cost

In [142]:
lambda_ = 0
cost = compute_cost (predictions, Y, R, W, X, lambda_)
cost

<tf.Tensor: shape=(), dtype=float64, numpy=175.2273905848433>

# Converting np to Tensor

In [143]:
#? Trainable Tensors
X = tf.Variable(X, dtype=tf.float64)
W = tf.Variable(W, dtype=tf.float64)
b = tf.Variable(b, dtype=tf.float64)

#? Constant Tensors:
Y = tf.convert_to_tensor(Y, dtype=tf.float64)
R = tf.convert_to_tensor(R, dtype=tf.float64)

In [144]:
learning_rate = 0.1

for epoch in range(200):
    
    with tf.GradientTape() as tape:
        predictions = W @ tf.transpose(X) + b[:, None]
    
        cost = compute_cost (predictions, Y, R, W, X, lambda_)

    gradients = tape.gradient(cost, [W, X, b])

    W.assign_sub(learning_rate * gradients[0])
    X.assign_sub(learning_rate * gradients[1])
    b.assign_sub(learning_rate * gradients[2])
    
    if epoch %20 == 0:
        print(f"Epoch {epoch}: Cost = {np.round(cost.numpy(), 3)}")

Epoch 0: Cost = 175.227
Epoch 20: Cost = 2.175
Epoch 40: Cost = 0.719
Epoch 60: Cost = 0.595
Epoch 80: Cost = 0.581
Epoch 100: Cost = 0.578
Epoch 120: Cost = 0.578
Epoch 140: Cost = 0.577
Epoch 160: Cost = 0.577
Epoch 180: Cost = 0.577


In [145]:
movies = [
    "Toy Story",
    "Matrix",
    "Titanic",
    "Avengers",
    "Shrek",
    "La La Land"
]

users, _ = Y.shape

for user_index in range(users):
    for movie_index, movie in enumerate(movies):
        if R[user_index, movie_index] == 0:
            print(f'Movie: {movie}, Predicted Rating: {predictions[user_index, movie_index].numpy()} \n Actual rating: {Y[user_index, movie_index]}')

Movie: Titanic, Predicted Rating: 4.285620203751259 
 Actual rating: 1.0
Movie: Shrek, Predicted Rating: -0.714305770652955 
 Actual rating: 1.0
Movie: Avengers, Predicted Rating: 5.107519499675901 
 Actual rating: 3.0
Movie: La La Land, Predicted Rating: 5.058277150071396 
 Actual rating: 5.0
Movie: Titanic, Predicted Rating: 2.6880960918753485 
 Actual rating: 1.0
Movie: Avengers, Predicted Rating: 4.815741515091622 
 Actual rating: 1.0
