In [78]:
import numpy as np
import tensorflow as tf

from utils import compute_cost

RANDOM_STATE = 36   

In [79]:
#? Movie Rating
Y = np.array([
#   Toy  Matrix  Titanic  Avengers  Shrek
    [5, 1, 1, 5, 4],  # Alice
    [1, 5, 2, 5, 1],  # Bob
    [5, 1, 5, 3, 5],  # Charlie
    [2, 5, 1, 4, 1]   # David
], dtype=np.float64)

#? Was Rated?
R = np.array([
    [1, 1, 0, 1, 1],
    [1, 1, 1, 1, 0],
    [1, 1, 1, 0, 1],
    [1, 1, 0, 1, 1]
], dtype=np.float64)

print(Y.shape)

(4, 5)


# Initialization of X, W, b Values

In [80]:
np.random.seed(RANDOM_STATE)

X = np.random.randn(5, 2,) #? Movies / Features
W = np.random.randn(4, 2,) #? Users / Features
b = np.zeros(4) #? Users 

X, W, b

(array([[ 0.67641327,  1.52109919],
        [-0.51187625,  1.15019464],
        [-0.59071681, -0.76876525],
        [-0.33500917,  0.09299944],
        [-1.37755311,  0.22791697]]),
 array([[-0.59016463, -1.29693989],
        [-1.59805879, -0.29740901],
        [-1.45155795, -0.19986179],
        [-0.55274563,  1.95845977]]),
 array([0., 0., 0., 0.]))

# Pedicting Move Ratings 
## With Linear Regression

In [81]:
predictions = W @ X.T + b[:, None]

print("X shape:", X.shape)
print("W shape:", W.shape)
print("b shape:", b.shape)
print("\nPredictions shape:", predictions.shape)

print(predictions)


X shape: (5, 2)
W shape: (4, 2)
b shape: (4,)

Predictions shape: (4, 5)
[[-2.3719694  -1.18964205  1.34566249  0.07709587  0.51738852]
 [-1.53333677  0.47593008  1.1726379   0.50770547  2.1336263 ]
 [-1.28586266  0.51313807  1.01110648  0.46769818  1.95404628]
 [ 2.60512709  2.53554728 -1.17907968  0.36731052  1.20780267]]


# Compute Cost

In [82]:
lambda_ = 0
cost = compute_cost (predictions, Y, R, W, X, lambda_)
cost

<tf.Tensor: shape=(), dtype=float64, numpy=113.93590261884334>

# Converting np to Tensor

In [83]:
#? Trainable Tensors
X = tf.Variable(X, dtype=tf.float64)
W = tf.Variable(W, dtype=tf.float64)
b = tf.Variable(b, dtype=tf.float64)

#? Constant Tensors:
Y = tf.convert_to_tensor(Y, dtype=tf.float64)
R = tf.convert_to_tensor(R, dtype=tf.float64)

In [84]:
learning_rate = 0.01

for epoch in range(200):
    
    with tf.GradientTape() as tape:
        predictions = W @ tf.transpose(X) + b[:, None]
    
        cost = compute_cost (predictions, Y, R, W, X, lambda_)

    gradients = tape.gradient(cost, [W, X, b])

    W.assign_sub(learning_rate * gradients[0])
    X.assign_sub(learning_rate * gradients[1])
    b.assign_sub(learning_rate * gradients[2])
    
    if epoch %20 == 0:
        print(f"Epoch {epoch}: Cost = {cost.numpy()}")

Epoch 0: Cost = 113.93590261884334
Epoch 20: Cost = 11.821409042074617
Epoch 40: Cost = 4.130557564362952
Epoch 60: Cost = 1.8893621452148195
Epoch 80: Cost = 1.1415626770780234
Epoch 100: Cost = 0.8056433003353891
Epoch 120: Cost = 0.6470055286945124
Epoch 140: Cost = 0.5665365324965721
Epoch 160: Cost = 0.5196549728368555
Epoch 180: Cost = 0.4873994248639919
